"""
Platform10 Regulator-Grade PDF Compliance Exporter
"""

import os
import json
import hashlib
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.units import inch

from platform10.governance.replay.regulator_replay import RegulatorReplay
from platform10.governance.signing.key_manager import KeyManager


class ReplayPDFExporter:

    def _public_key_fingerprint(self) -> str:
        with open("replay_public_key.pem", "rb") as f:
            key_data = f.read()
        return hashlib.sha256(key_data).hexdigest()

    def export(self, trace_id: str) -> str:
        r = RegulatorReplay()

        file_path = os.path.join("replay_logs", f"{trace_id}.json")
        if not os.path.exists(file_path):
            raise FileNotFoundError("Replay not found")

        with open(file_path, "r") as f:
            data = json.load(f)

        pdf_path = f"replay_logs/{trace_id}_compliance_report.pdf"

        doc = SimpleDocTemplate(pdf_path)
        elements = []
        styles = getSampleStyleSheet()

        # Title
        elements.append(Paragraph("<b>Platform10 Governed Agent Runtime</b>", styles["Title"]))
        elements.append(Paragraph("Cryptographically Sealed Compliance Artifact", styles["Normal"]))
        elements.append(Spacer(1, 0.3 * inch))

        # Case Metadata
        elements.append(Paragraph("<b>Trace Metadata</b>", styles["Heading2"]))
        elements.append(Spacer(1, 0.2 * inch))
        elements.append(Paragraph(f"Trace ID: {trace_id}", styles["Normal"]))
        elements.append(Paragraph(f"Timestamp: {data.get('timestamp')}", styles["Normal"]))
        elements.append(Spacer(1, 0.3 * inch))

        # Final Risk
        final_context = data.get("final_context", {})
        risk = final_context.get("risk", "N/A")

        elements.append(Paragraph("<b>Final Risk Determination</b>", styles["Heading2"]))
        elements.append(Spacer(1, 0.2 * inch))
        elements.append(Paragraph(f"Risk Classification: {risk}", styles["Normal"]))
        elements.append(Spacer(1, 0.3 * inch))

        # Signals Table
        elements.append(Paragraph("<b>Signal Breakdown</b>", styles["Heading2"]))
        elements.append(Spacer(1, 0.2 * inch))

        signals = final_context.get("signals", [])
        table_data = [["Agent", "Signal Type", "Risk"]]

        for s in signals:
            table_data.append([
                s.get("agent"),
                s.get("signal_type"),
                s.get("risk"),
            ])

        table = Table(table_data, hAlign="LEFT")
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
        ]))

        elements.append(table)
        elements.append(Spacer(1, 0.4 * inch))

        # Verification Summary
        elements.append(Paragraph("<b>Cryptographic Verification Summary</b>", styles["Heading2"]))
        elements.append(Spacer(1, 0.2 * inch))

        integrity_ok = r.verify_integrity(trace_id)
        signature_ok = r.verify_signature(trace_id)
        chain_ok = r.verify_chain()

        elements.append(Paragraph(f"Integrity Verification: {'VERIFIED' if integrity_ok else 'FAILED'}", styles["Normal"]))
        elements.append(Paragraph(f"Digital Signature: {'VERIFIED' if signature_ok else 'FAILED'}", styles["Normal"]))
        elements.append(Paragraph(f"Ledger Chain Status: {'VERIFIED' if chain_ok else 'FAILED'}", styles["Normal"]))
        elements.append(Spacer(1, 0.3 * inch))

        # Hash & Signature
        elements.append(Paragraph("<b>Integrity Hash</b>", styles["Heading3"]))
        elements.append(Paragraph(data.get("integrity_hash"), styles["Normal"]))
        elements.append(Spacer(1, 0.2 * inch))

        elements.append(Paragraph("<b>Digital Signature (Ed25519)</b>", styles["Heading3"]))
        elements.append(Paragraph(data.get("signature"), styles["Normal"]))
        elements.append(Spacer(1, 0.3 * inch))

        # Public Key Fingerprint
        fingerprint = self._public_key_fingerprint()
        elements.append(Paragraph("<b>Public Key Fingerprint (SHA256)</b>", styles["Heading3"]))
        elements.append(Paragraph(fingerprint, styles["Normal"]))
        elements.append(Spacer(1, 0.5 * inch))

        # Footer
        elements.append(Paragraph(
            "This compliance artifact was generated by Platform10 Governed Agent Runtime. "
            "The record is cryptographically sealed using SHA256 integrity hashing and "
            "Ed25519 digital signatures. Any tampering invalidates verification.",
            styles["Normal"]
        ))

        doc.build(elements)
        return pdf_path
        